=== EduardoPMSauces/PROYECTO1920_LMSGI_EPM/PROYECTO1920_LMSGI_EPM/practicas/xml/15/xml15.xsd
<?xml version="1.0" encoding="UTF-8"?>


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="registro">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="datoPersonal">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nombre" type="xs:string"/>
							<xs:element name="apellido" type="xs:string"/>
							<xs:element name="fechanac" type="xs:string"/>
							<xs:element name="sexo" type="xs:string"/>
							<xs:element name="direccion" type="xs:string"/>
							<xs:element name="ciudad" type="xs:string"/>
							<xs:element name="provincia" type="xs:string"/>
							<xs:element name="codigoPostal" type="xs:string"/>
							<xs:element name="telefono" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="datosCuenta">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="correo" type="xs:string"/>
							<xs:element name="usuario" type="xs:string"/>
							<xs:element name="contrasenya" type="xs:string"/>
							<xs:element name="preguntaSecreta" type="xs:string"/>
							<xs:element name="colorPerfil" type="xs:string"/>
							<xs:element name="foto" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="otroDato">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="conocer" type="xs:string"/>
							<xs:element name="observacion" type="xs:string"/>
							<xs:element name="valorar" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== EduardoPMSauces/PROYECTO1920_LMSGI_EPM/PROYECTO1920_LMSGI_EPM/practicas/xml/15/xml15.xml
<?xml version="1.0" encoding="UTF-8"?>



<registro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xml15.xsd">
	<datoPersonal>
		<nombre></nombre>
		<apellido></apellido>
		<fechanac></fechanac>
		<sexo></sexo>
		<direccion></direccion>
		<ciudad></ciudad>
		<provincia></provincia>
		<codigoPostal></codigoPostal>
		<telefono></telefono>
	</datoPersonal>
	<datosCuenta>
		<correo></correo>
		<usuario></usuario>
		<contrasenya></contrasenya>
		<preguntaSecreta></preguntaSecreta>
		<colorPerfil></colorPerfil>
		<foto></foto>
	</datosCuenta>
	<otroDato>
		<conocer></conocer>
		<observacion></observacion>
		<valorar></valorar>
	</otroDato>
</registro>
