<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE Company [
	<!ELEMENT Company (Employee*)>
	<!ELEMENT Employee (FirstName, LastName, ContactNo, Email*, Address)>
	<!ELEMENT FirstName (#PCDATA)>
	<!ELEMENT LastName (#PCDATA)>
	<!ELEMENT ContactNo (#PCDATA)>
	<!ELEMENT Email (#PCDATA)>
	<!ELEMENT Address (City, State, Zip)>
	<!ELEMENT City (#PCDATA)>
	<!ELEMENT State (#PCDATA)>
	<!ELEMENT Zip (#PCDATA)>
]>


<Company>
	<Employee>
		<FirstName></FirstName>
		<LastName></LastName>
		<ContactNo></ContactNo>
		<Email></Email>
		<Address>
			<City></City>
			<State></State>
			<Zip></Zip>
		</Address>
	</Employee>
</Company>