<?xml version="1.0" encoding="UTF-8" standalone="no"?>	

<!DOCTYPE mail [
	<!ELEMENT mail (remitente, destinatario, asunto?, mensaje, adjuntos?) >
	<!ELEMENT remitente (#PCDATA)>
	<!ELEMENT destinatario (correo+)>
	<!ELEMENT correo (#PCDATA)>
	<!ELEMENT asunto (#PCDATA)>
	<!ELEMENT mensaje (#PCDATA)>
	<!ELEMENT adjuntos (image+)>
	<!ELEMENT image (tipo, nombre)>
	<!ELEMENT tipo (#PCDATA)>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT fecha (#PCDATA)>
	<!ATTLIST mail xmlns:xsi CDATA #IMPLIED>
	<!ATTLIST mail xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
]>

<mail xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="xsd01.xsd">													
	<fecha>2020-01-14</fecha>
	<remitente>marodriguezn@educa.jcyl.es</remitente>
	<destinatario>
		<correo>eduardo@educa.jcyl.es</correo>
		<correo>maria@educa.jcyl.es</correo>
	</destinatario>
	<asunto>Fiesta de fin de curso</asunto>
	<mensaje> A las 20:00 en ...</mensaje>
	<adjuntos>
		<image>
			<tipo>image/png</tipo>
			<nombre>foto1.png</nombre>
		</image>
		<image>
			<tipo>image/png</tipo>
			<nombre>foto2.png</nombre>
		</image>
	</adjuntos>
</mail>